[theme]
base="light"
primaryColor="#10b981"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0fdf4"
textColor="#064e3b"
font="sans serif"

[server]
headless = true
enableCORS = false

[ui]
hideTopBar = false
